INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (251, 3, "Фізика", "2010-02-11", "Vel adipisci tempore quibusdam ipsam neque.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (254, 1, "Дієтологія", "1988-10-22", "Nulla voluptatibus culpa nisi libero amet sapiente quis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (254, 4, "Дієтологія", "2009-05-06", "Magni accusantium consequuntur.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (266, 3, "Фізика", "1992-10-06", "Sit repellat reprehenderit aliquam nisi.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (273, 2, "ЕсКюЕль", "1997-02-09", "Labore minima nulla vel placeat dicta.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (273, 2, "ЕсКюЕль", "1995-10-27", "Alias autem veritatis autem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (275, 1, "ДжаваСкріпт", "2015-07-06", "Cum perferendis deserunt architecto vitae sapiente deserunt.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (275, 2, "ДжаваСкріпт", "2004-06-27", "Tenetur ad facilis enim occaecati voluptatem molestias veritatis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (279, 1, "Хімія", "1978-01-28", "Provident omnis dolor id tenetur.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (279, 2, "Хімія", "1977-05-17", "Velit facere placeat non rerum aliquid.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (283, 1, "Література", "2008-07-08", "Maxime facilis nemo ex possimus blanditiis laudantium cumque.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (283, 3, "Література", "1980-04-19", "Ullam odio hic soluta.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (293, 4, "ЕсКюЕль", "1980-01-19", "Quis error nobis velit laborum neque omnis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (300, 4, "ЕсКюЕль", "2004-02-25", "Excepturi quod quod enim.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (300, 2, "ЕсКюЕль", "1970-01-01", "Repellat cum unde amet esse nihil.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (305, 3, "Фізика", "1999-08-11", "Maxime incidunt velit.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (305, 4, "Фізика", "1973-02-18", "Ullam mollitia dolorem sunt.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (314, 4, "Дієтологія", "1977-02-26", "Sint delectus repellendus corporis non nulla.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (320, 4, "ДжаваСкріпт", "2020-03-07", "Doloremque commodi impedit nulla.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (328, 3, "ДжаваСкріпт", "2009-09-22", "Expedita deleniti reprehenderit pariatur omnis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (328, 1, "ДжаваСкріпт", "2017-03-20", "Illum quam exercitationem assumenda repudiandae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (329, 2, "Література", "2001-06-20", "Minus fugit suscipit nobis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (329, 1, "Література", "1988-07-08", "Recusandae perspiciatis est rem atque.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (334, 2, "Хімія", "2006-10-01", "Magnam velit esse occaecati dolores fuga.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (334, 1, "Хімія", "1980-11-06", "Vel officiis esse praesentium.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (336, 3, "Література", "2019-10-01", "Fugiat cum aut voluptatem neque.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (338, 4, "Хімія", "2002-01-05", "In assumenda adipisci.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (346, 1, "ЕсКюЕль", "1993-03-12", "Ipsam provident quis alias debitis distinctio.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (348, 2, "ЕсКюЕль", "2009-07-09", "Quod voluptatibus tenetur esse id.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (358, 3, "ЕсКюЕль", "1983-03-19", "Ipsum fugiat a ipsum eum architecto quis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (358, 4, "ЕсКюЕль", "2005-07-31", "Doloribus error nemo voluptatem porro soluta.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (364, 4, "Дієтологія", "2002-01-18", "Natus laboriosam iure incidunt magnam dolorem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (369, 3, "Література", "1976-05-15", "Aliquid necessitatibus nihil officia nisi.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (369, 3, "Література", "1990-07-15", "Laboriosam laudantium repudiandae saepe nemo tempore consequuntur.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (370, 4, "Хімія", "1983-05-31", "Similique impedit ea alias consequatur rem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (370, 1, "Хімія", "1987-05-31", "Iste quam voluptatum omnis dolor fugit quam.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (371, 3, "Математика", "2004-08-12", "Delectus maxime expedita similique soluta.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (376, 1, "ЕсКюЕль", "2021-09-01", "Fugit nulla labore.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (377, 3, "Фізика", "2012-04-06", "Fugiat incidunt perspiciatis minima eveniet blanditiis repellat.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (389, 4, "Дієтологія", "1995-04-26", "Voluptates ab illum.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (389, 4, "Дієтологія", "1977-03-15", "Asperiores nesciunt magnam corrupti soluta sequi.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (390, 4, "Дієтологія", "1985-01-14", "Ab sunt earum officia non repellendus exercitationem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (398, 4, "Хімія", "2005-06-04", "Consequatur debitis iure autem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (404, 3, "Хімія", "1997-07-31", "Natus aut nesciunt.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (404, 3, "Хімія", "1973-11-27", "Eveniet repellendus atque temporibus molestias.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (405, 3, "ЕсКюЕль", "1978-04-05", "Possimus totam aliquid consectetur nemo blanditiis ipsum.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (405, 3, "ЕсКюЕль", "2000-03-09", "Rem ipsa vel cum.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (420, 2, "Хімія", "2012-06-07", "Eveniet ut exercitationem blanditiis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (420, 4, "Хімія", "2014-09-08", "Fugit iste eum odio accusamus.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (423, 1, "Щосьлогія", "2007-11-21", "Iste voluptatibus incidunt molestiae ex voluptatum est excepturi.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (427, 2, "ЕсКюЕль", "1978-07-23", "Inventore harum autem id nihil aperiam.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (427, 1, "ЕсКюЕль", "1983-11-09", "Quaerat architecto eligendi optio.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (435, 3, "Дієтологія", "2014-08-09", "Ad itaque aperiam tempore.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (435, 3, "Дієтологія", "1991-02-25", "Nihil dicta suscipit explicabo eaque pariatur corporis nesciunt.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (442, 3, "Щосьлогія", "2001-02-03", "Placeat ipsa eum optio doloribus accusamus perspiciatis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (442, 2, "Щосьлогія", "1977-04-19", "Corrupti vitae facilis impedit.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (446, 3, "ЕсКюЕль", "2004-05-11", "Est maiores cum aut quo soluta recusandae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (446, 2, "ЕсКюЕль", "1990-05-13", "Dolorem doloremque assumenda rem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (450, 3, "ДжаваСкріпт", "2002-06-08", "Similique facere dolores necessitatibus repellendus iste.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (450, 3, "ДжаваСкріпт", "2005-06-11", "Rerum mollitia voluptate ipsum.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (451, 3, "ДжаваСкріпт", "2003-02-07", "Repellat officiis architecto.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (453, 3, "Щосьлогія", "2020-08-18", "Laboriosam aspernatur vero nostrum.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (453, 4, "Щосьлогія", "2004-04-22", "Provident ullam cupiditate earum vel accusantium.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (458, 2, "Література", "2005-10-14", "Minus cupiditate corrupti illo aliquam consequatur non.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (458, 3, "Література", "2016-05-29", "Suscipit ullam esse provident nisi quia.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (473, 3, "ДжаваСкріпт", "1973-04-16", "Cum tempora veniam repellat quae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (473, 2, "ДжаваСкріпт", "2005-03-16", "Provident magnam consectetur soluta minus.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (493, 4, "ДжаваСкріпт", "2005-06-09", "Quod vel debitis dolorem eligendi earum temporibus.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (493, 3, "ДжаваСкріпт", "1974-05-11", "Totam quos voluptas itaque voluptates.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (503, 1, "ЕсКюЕль", "2004-01-10", "Perspiciatis consectetur odit doloribus dolore soluta.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (503, 4, "ЕсКюЕль", "1995-06-14", "Quam eaque magnam in quaerat doloribus adipisci.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (511, 1, "Література", "1992-04-16", "Facilis illum beatae libero iusto repudiandae ex.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (513, 3, "Щосьлогія", "2019-06-05", "Amet fugiat modi recusandae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (523, 1, "Дієтологія", "1968-12-21", "Aut deleniti magni adipisci.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (529, 3, "Хімія", "2011-05-11", "Sed laboriosam sequi explicabo ratione.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (529, 4, "Хімія", "2003-08-26", "Veniam numquam optio doloribus quasi deserunt itaque minima.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (530, 2, "Фізика", "1989-02-26", "Suscipit numquam minus.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (565, 1, "Література", "1991-12-09", "Delectus provident distinctio nam sit.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (565, 3, "Література", "2008-03-11", "Nostrum dignissimos blanditiis.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (572, 4, "Математика", "2002-08-23", "Perferendis at eligendi assumenda fugit rerum vitae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (572, 2, "Математика", "2018-11-19", "Voluptates provident impedit voluptas incidunt fuga.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (581, 3, "ЕсКюЕль", "2000-06-25", "Inventore nulla nostrum sit.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (583, 2, "Дієтологія", "2015-11-26", "Molestiae aliquid assumenda possimus possimus numquam labore.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (584, 2, "Хімія", "2002-08-30", "Assumenda doloremque pariatur.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (584, 3, "Хімія", "1990-06-12", "Quidem dicta ipsam consequatur.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (592, 3, "Математика", "2011-10-12", "Impedit temporibus aliquid temporibus iste eos eligendi.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (592, 3, "Математика", "1977-01-04", "Doloremque nulla rem recusandae quae porro.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (594, 4, "Фізика", "1979-08-05", "Tempora facilis adipisci harum molestiae nemo.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (596, 4, "Щосьлогія", "1996-04-11", "Odit quis animi eaque.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (597, 2, "Математика", "1974-04-17", "Inventore fugiat asperiores.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (597, 2, "Математика", "2004-08-22", "Occaecati quia velit nesciunt doloribus iure culpa.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (599, 1, "Хімія", "1980-08-07", "Facere nesciunt fugit sit amet.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (600, 3, "ЕсКюЕль", "1970-11-04", "Praesentium voluptate deserunt eum quos dicta distinctio.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (603, 3, "Математика", "2006-03-31", "Quaerat culpa iusto perferendis esse a.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (604, 1, "ДжаваСкріпт", "1995-08-25", "Cupiditate libero qui corporis distinctio qui.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (608, 3, "Математика", "1972-06-12", "Ratione tempore ea odit magnam.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (609, 1, "Математика", "2013-11-10", "Vitae dolore tempore eos quis ad quae.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (610, 2, "Математика", "1993-06-19", "Aliquid quisquam aliquam voluptates sunt numquam quaerat et.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (620, 2, "Література", "1973-09-30", "Molestias repellat possimus.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (622, 3, "ДжаваСкріпт", "1982-09-09", "Pariatur similique ipsa quidem.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (625, 4, "Дієтологія", "1989-11-13", "Rem eaque sint voluptas quaerat.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (626, 1, "ДжаваСкріпт", "2011-11-10", "Commodi enim accusamus iure quia soluta fuga.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (630, 1, "Література", "2004-07-31", "Eos aliquam cum vel est.");
INSERT INTO `person_sci_career` (`person_id`, `sci_title_id`, `science`, `date`, `work_title`) VALUES (630, 3, "Література", "1986-11-20", "Modi dolorem cupiditate voluptas assumenda.")